package com.github.tompower.spring.boot.flyway.migrate.messages;

public class Messages {

    public static final String MIGRATIONS_COMPLETED = " migrations completed";
    public static final String NO_MIGRATIONS_NEEDED = "no migrations needed";
    public static final String MIGRATION_SUCCESSFUL = "Migration successful: ";
    public static final String VALIDATION_SUCCESSFUL = "Validation successful: ";
    public static final String CREATED = "Migration file created: ";
    public static final String EXISTS = "Migration file not created as file exists: ";
    public static final String UP_TO_DATE = "Migration file not created as no scripts generated by hbm2ddl update, database up to date?";
    public static final String CANNOT_CREATE = "Migration file not created as cannot getInstance the migration file: ";
    public static final String LINE = "---";
    public static final String SPACE = " ";

    public static String getMigrationMessage(int i) {
        return i == 0 ? NO_MIGRATIONS_NEEDED : i + MIGRATIONS_COMPLETED;
    }
}
